#!/bin/bash

MUTE=$(pactl get-sink-mute @DEFAULT_SINK@)

class() {
if [ "$MUTE" = "Mute: no" ]; then
    echo "unmuted"
else
    echo "muted"
fi

}


icon () {
if [ "$MUTE" = "Mute: no" ]; then
    echo "unmuted"
else
    echo "muted"
fi
}
